CREATE OR REPLACE FUNCTION public.create_synthea_table_postgres(OUT errormsg text)
RETURNS text
LANGUAGE plpgsql
AS $function$
BEGIN
--	dropping synthea tables if they exist
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_DEVICES CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_OBSERVATIONS CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_ENCOUNTERS CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_MEDICATIONS CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_IMMUNIZATIONS CASCADE ';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_CAREPLANS CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_CONDITIONS CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_PROCEDURES CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_PROVIDERS CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_PATIENTS CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_ALLERGIES CASCADE';
EXECUTE 'DROP TABLE IF EXISTS SYNTHEA_ORGANIZATIONS CASCADE';

raise notice 'creating table SYNTHEA_DEVICES';
EXECUTE 'create table SYNTHEA_DEVICES  (
START_DEV DATE NOT NULL,
STOP DATE NULL,
PATIENT varchar(50) NOT NULL,
ENCOUNTER varchar(50) NOT NULL,
CODE int NOT NULL,
DESCRIPTION varchar(100) NOT NULL,
UDI varchar(100) NOT NULL
)';

raise notice 'creating table SYNTHEA_ORGANIZATIONS';
EXECUTE 'create table SYNTHEA_ORGANIZATIONS  (
Id varchar(50) NOT NULL,
NAME varchar(100) NOT NULL,
ADDRESS varchar(50) NOT NULL,
CITY varchar(50) NOT NULL,
STATE varchar(50) NOT NULL,
ZIP varchar(50) NOT NULL,
LAT float NOT NULL,
LON float NOT NULL,
PHONE varchar(50) NULL,
REVENUE float NOT NULL,
UTILIZATION int NOT NULL

)';

raise notice 'creating table SYNTHEA_PATIENTS';
EXECUTE 'create table SYNTHEA_PATIENTS  (
id varchar(1000) NULL,
birthdate date NULL,
deathdate date NULL,
ssn varchar(100) NULL,
drivers varchar(100) NULL,
passport varchar(100) NULL,
prefix varchar(100) NULL,
first varchar(100) NULL,
last varchar(100) NULL,
suffix varchar(100) NULL,
maiden varchar(100) NULL,
marital varchar(100) NULL,
race varchar(100) NULL,
ethnicity varchar(100) NULL,
gender varchar(100) NULL,
birthplace varchar(100) NULL,
address varchar(100) NULL,
city varchar(100) NULL,
state varchar(100) NULL,
zip varchar(100) NULL

)';

raise notice 'creating table SYNTHEA_PROVIDERS';
EXECUTE 'create table SYNTHEA_PROVIDERS  (
Id varchar(50) NOT NULL,
ORGANIZATION varchar(50) NOT NULL,
NAME varchar(50) NOT NULL,
GENDER varchar(50) NOT NULL,
SPECIALITY varchar(50) NOT NULL,
ADDRESS varchar(50) NOT NULL,
CITY varchar(50) NOT NULL,
STATE varchar(50) NOT NULL,
ZIP varchar(50) NOT NULL,
LAT float NOT NULL,
LON float NOT NULL,
UTILIZATION int NOT NULL

)';

raise notice 'creating table SYNTHEA_MEDICATIONS';
EXECUTE 'create table SYNTHEA_MEDICATIONS  (
START_MED DATE NOT NULL,
STOP DATE NULL,
PATIENT varchar(50) NOT NULL,
PAYER varchar(50) NULL,
ENCOUNTER varchar(50) NOT NULL,
CODE varchar(50) NOT NULL,
DESCRIPTION varchar(200) NOT NULL,
BASE_COST float NULL,
PAYER_COVERAGE float NULL,
DISPENSES int NULL,
TOTALCOST float NULL,
REASONCODE varchar(50) NULL,
REASONDESCRIPTION varchar(200) NULL

)';

raise notice 'creating table SYNTHEA_CONDITIONS';
EXECUTE 'create table SYNTHEA_CONDITIONS  (
START_CON DATE NOT NULL,
STOP DATE NULL,
PATIENT varchar(50) NOT NULL,
ENCOUNTER varchar(50) NOT NULL,
CODE float NOT NULL,
DESCRIPTION varchar(100) NOT NULL

)';

raise notice 'creating table SYNTHEA_PROCEDURES';
EXECUTE 'create table SYNTHEA_PROCEDURES  (
DATE_PROC DATE NOT NULL,
PATIENT varchar(50) NOT NULL,
ENCOUNTER varchar(50) NOT NULL,
CODE varchar(50) NOT NULL,
DESCRIPTION varchar(150) NOT NULL,
BASE_COST float NULL,
REASONCODE varchar(100) NULL,
REASONDESCRIPTION varchar(150) NULL

)';

raise notice 'creating table SYNTHEA_CAREPLANS';
EXECUTE 'create table SYNTHEA_CAREPLANS  (
Id varchar(50) NOT NULL,
START_CP DATE NOT NULL,
STOP DATE NULL,
PATIENT varchar(50) NOT NULL,
ENCOUNTER varchar(50) NOT NULL,
CODE float NOT NULL,
DESCRIPTION varchar(100) NOT NULL,
REASONCODE float NULL,
REASONDESCRIPTION varchar(100) NULL
)';
raise notice 'creating table SYNTHEA_ENCOUNTERS';
EXECUTE 'create table SYNTHEA_ENCOUNTERS  (
Id varchar(50) NOT NULL,
START_ENC  DATE NOT NULL,
STOP DATE  NULL,
PATIENT varchar(50) NOT NULL,
ORGANIZATION varchar(50) NULL,
PROVIDER varchar(50) NULL,
PAYER varchar(50) NULL,
ENCOUNTERCLASS varchar(50) NULL,
CODE int NULL,
DESCRIPTION varchar(100) NULL,
BASE_ENCOUNTER_COST float NULL,
TOTAL_CLAIM_COST float NULL,
PAYER_COVERAGE float NULL,
REASONCODE float NULL,
REASONDESCRIPTION varchar(100) NULL
)';

raise notice 'creating table SYNTHEA_OBSERVATIONS ';
EXECUTE 'create table SYNTHEA_OBSERVATIONS  (
DATE_OB DATE NOT NULL,
PATIENT varchar(50) NOT NULL,
ENCOUNTER varchar(50) NULL,
CODE varchar(50) NOT NULL,
DESCRIPTION varchar(200) NOT NULL,
VALUE varchar(100) NULL,
UNITS varchar(50) NULL,
TYPE varchar(50) NULL
)';

raise notice 'creating table SYNTHEA_ALLERGIES ';
EXECUTE 'create table SYNTHEA_ALLERGIES  (
START_AL DATE NOT NULL,
STOP DATE NULL,
PATIENT varchar(50) NOT NULL,
ENCOUNTER varchar(50) NOT NULL,
CODE  int NOT NULL,
DESCRIPTION varchar(50) NOT NULL
)';

raise notice 'creating table SYNTHEA_IMMUNIZATIONS ';
execute 'create table SYNTHEA_IMMUNIZATIONS  (
DATE_IM DATE NOT NULL,
PATIENT varchar(50) NOT NULL,
ENCOUNTER varchar(50) NOT NULL,
CODE int NOT NULL,
DESCRIPTION varchar(100) NOT NULL,
BASE_COST float NULL
)';


EXCEPTION
WHEN OTHERS THEN
RAISE EXCEPTION 'An error was encountered - % -ERROR- %',SQLSTATE,SQLERRM;
END;
$function$
;